
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 13 14:21:10 CET 2015
//----------------------------------------------------

package sml.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQUENCE = 19;
  public static final int PLUS = 3;
  public static final int RPAREN = 6;
  public static final int EQUAL = 9;
  public static final int SEMI = 2;
  public static final int PLAY = 16;
  public static final int CHORD = 18;
  public static final int TEMPO = 15;
  public static final int END = 14;
  public static final int RACCOL = 8;
  public static final int LPAREN = 5;
  public static final int LETTER = 21;
  public static final int IDENTIFIANT = 24;
  public static final int BEGIN = 13;
  public static final int COMA = 10;
  public static final int SCALE = 17;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int LACCOL = 7;
  public static final int COMPLEXNOTE = 22;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int SCALENAME = 25;
  public static final int LET = 11;
  public static final int REST = 20;
  public static final int ENS = 12;
}

